# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Finder
version:      0.03
version_from: lib/File/Finder.pm
installdirs:  site
requires:
    Test::More:                    0
    Text::Glob:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
